# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Category.create([
    { name: 'Business & Management' },
    { name: 'Engineering' },
    { name: 'Science' },
    { name: 'Health Care' },
    { name: 'Career Development' },
    { name: 'Life Essentials' },
    { name: 'Language' },
    { name: 'Design' },
    { name: 'Art' },
    { name: 'Fitness' }
])

Instructor.create([
    { name: 'Instructor One', title: 'Instructor', linkedin: 'http://linkedinexample.com', email: 'example@gmail.com', img: 'https://i.imgur.com/DRlNORt.png', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.' },
    { name: 'Instructor Two', title: 'Instructor', linkedin: 'http://linkedinexample.com', email: 'example@gmail.com', img: 'https://i.imgur.com/DRlNORt.png', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.' },
    { name: 'Instructor Three', title: 'Instructor', linkedin: 'http://linkedinexample.com', email: 'example@gmail.com', img: 'https://i.imgur.com/DRlNORt.png', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.' },
    { name: 'Instructor Four', title: 'Instructor', linkedin: 'http://linkedinexample.com', email: 'example@gmail.com', img: 'https://i.imgur.com/DRlNORt.png', bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.' }
])

Course.create([
    { title: 'Introduction to Software Engineering', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', img: 'https://i.imgur.com/xx0dtmu.jpg', what_will_you_learn: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', main_content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', main_video: 'https://www.youtube.com/watch?v=n9V_1X8uGZM', practice: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', category_id: 2, instructor_id: 1 },
    { title: 'Business Foundation', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', img: 'https://i.imgur.com/xx0dtmu.jpg', what_will_you_learn: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', main_content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', main_video: 'https://www.youtube.com/watch?v=n9V_1X8uGZM', practice: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', category_id: 1, instructor_id: 1 }, 
    { title: 'The Art Of Photography', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', img: 'https://i.imgur.com/xx0dtmu.jpg', what_will_you_learn: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', main_content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', main_video: 'https://www.youtube.com/watch?v=n9V_1X8uGZM', practice: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', category_id: 9, instructor_id: 2 },
    { title: 'Advanced Photography', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', img: 'https://i.imgur.com/xx0dtmu.jpg', what_will_you_learn: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', main_content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', main_video: 'https://www.youtube.com/watch?v=n9V_1X8uGZM', practice: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', category_id: 9, instructor_id: 2 },
    { title: 'Painting For Beginners', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', img: 'https://i.imgur.com/xx0dtmu.jpg', what_will_you_learn: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', main_content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', main_video: 'https://www.youtube.com/watch?v=n9V_1X8uGZM', practice: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', category_id: 9, instructor_id: 2 },
    { title: 'Chemistry Principles', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', img: 'https://i.imgur.com/xx0dtmu.jpg', what_will_you_learn: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', main_content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', main_video: 'https://www.youtube.com/watch?v=n9V_1X8uGZM', practice: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', category_id: 3, instructor_id: 3 },
    { title: 'Astronomy ', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', img: 'https://i.imgur.com/xx0dtmu.jpg', what_will_you_learn: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', main_content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', main_video: 'https://www.youtube.com/watch?v=n9V_1X8uGZM', practice: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', category_id: 3, instructor_id: 3 },
    { title: 'Anatomy', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', img: 'https://i.imgur.com/xx0dtmu.jpg', what_will_you_learn: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', main_content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', main_video: 'https://www.youtube.com/watch?v=n9V_1X8uGZM', practice: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.' },
    { title: 'Patient Care', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', img: 'https://i.imgur.com/xx0dtmu.jpg', what_will_you_learn: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', main_content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', main_video: 'https://www.youtube.com/watch?v=n9V_1X8uGZM', practice: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', category_id: 4, instructor_id: 4 },
    { title: 'Self Defense', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', img: 'https://i.imgur.com/xx0dtmu.jpg', what_will_you_learn: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', main_content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', main_video: 'https://www.youtube.com/watch?v=n9V_1X8uGZM', practice: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', category_id: 6, instructor_id: 4 },
    { title: 'Job Search', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', img: 'https://i.imgur.com/xx0dtmu.jpg', what_will_you_learn: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', main_content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', main_video: 'https://www.youtube.com/watch?v=n9V_1X8uGZM', practice: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', category_id: 5, instructor_id: 1 },
    { title: 'Resumes & Cover Letters', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', img: 'https://i.imgur.com/xx0dtmu.jpg', what_will_you_learn: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', main_content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', main_video: 'https://www.youtube.com/watch?v=n9V_1X8uGZM', practice: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', category_id: 5, instructor_id: 1 },
    { title: 'Networking', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', img: 'https://i.imgur.com/xx0dtmu.jpg', what_will_you_learn: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', main_content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', main_video: 'https://www.youtube.com/watch?v=n9V_1X8uGZM', practice: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', category_id: 1, instructor_id: 1 },
    { title: 'Nutrition & Wellness', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', img: 'https://i.imgur.com/xx0dtmu.jpg', what_will_you_learn: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', main_content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', main_video: 'https://www.youtube.com/watch?v=n9V_1X8uGZM', practice: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', category_id: 10, instructor_id: 3 },
    { title: 'Full Body Workout', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', img: 'https://i.imgur.com/xx0dtmu.jpg', what_will_you_learn: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', main_content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', main_video: 'https://www.youtube.com/watch?v=n9V_1X8uGZM', practice: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', category_id: 10, instructor_id: 3 },
    { title: 'Learn Boxing', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', img: 'https://i.imgur.com/xx0dtmu.jpg', what_will_you_learn: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', main_content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', main_video: 'https://www.youtube.com/watch?v=n9V_1X8uGZM', practice: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', category_id: 10, instructor_id: 3 },
    { title: 'Dance', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', img: 'https://i.imgur.com/xx0dtmu.jpg', what_will_you_learn: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', main_content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', main_video: 'https://www.youtube.com/watch?v=n9V_1X8uGZM', practice: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', category_id: 9, instructor_id: 4 },
    { title: 'UX Design', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', img: 'https://i.imgur.com/xx0dtmu.jpg', what_will_you_learn: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', main_content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', main_video: 'https://www.youtube.com/watch?v=n9V_1X8uGZM', practice: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', category_id: 8, instructor_id: 2 },
    { title: 'Graphic Design', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', img: 'https://i.imgur.com/xx0dtmu.jpg', what_will_you_learn: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', main_content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', main_video: 'https://www.youtube.com/watch?v=n9V_1X8uGZM', practice: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', category_id: 8, instructor_id: 2 },
    { title: 'Filing Taxes', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', img: 'https://i.imgur.com/xx0dtmu.jpg', what_will_you_learn: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', main_content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', main_video: 'https://www.youtube.com/watch?v=n9V_1X8uGZM', practice: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', category_id: 6, instructor_id: 1 },
    { title: 'Data Analysis', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', img: 'https://i.imgur.com/xx0dtmu.jpg', what_will_you_learn: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', main_content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', main_video: 'https://www.youtube.com/watch?v=n9V_1X8uGZM', practice: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', category_id: 1, instructor_id: 2 },
    { title: 'Managing Your Money From Saving to Investing', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', img: 'https://i.imgur.com/xx0dtmu.jpg', what_will_you_learn: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', main_content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', main_video: 'https://www.youtube.com/watch?v=n9V_1X8uGZM', practice: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.', category_id: 6, instructor_id: 3 }
])

User.create([
    { first_name: 'test', last_name: 'test', username: 'test', password: 'test' },
    { first_name: 'maha', last_name: 'mahmood', username: 'maha', password: 'maha' }
])

Ledger.create([
    { user_id: 1, course_id: 1 },
    { user_id: 1, course_id: 3 },
    { user_id: 1, course_id: 10 },
    { user_id: 2, course_id: 9 },
    { user_id: 2, course_id: 5 },
    { user_id: 2, course_id: 12 }
])``